// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo6k1C7X5YU0LCG5UOauKaD7KAwEhpNL8',
    appId: '1:960790952122:web:56427f6ef93cb2e9076a83',
    messagingSenderId: '960790952122',
    projectId: 'live-score-app-f',
    authDomain: 'live-score-app-f.firebaseapp.com',
    storageBucket: 'live-score-app-f.firebasestorage.app',
    measurementId: 'G-C18KVYDRPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPzurekhdy0YDO8ZetKpm3CG79b3OivNY',
    appId: '1:960790952122:android:4214ffc4ea957d8e076a83',
    messagingSenderId: '960790952122',
    projectId: 'live-score-app-f',
    storageBucket: 'live-score-app-f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmDD8moIqLDHOh1zl-PD5UpG81YWtXVBo',
    appId: '1:960790952122:ios:aea017ee3d6b0627076a83',
    messagingSenderId: '960790952122',
    projectId: 'live-score-app-f',
    storageBucket: 'live-score-app-f.firebasestorage.app',
    iosBundleId: 'com.livescore.liveScore',
  );
}
